---
- name: Check whether npm/nodejs installed
  command: 'which npm' 
  register: npm_installed
  ignore_errors: yes

- name: Install NPM package 
  ansible.builtin.package:
    name: npm
    state: present
  when: npm_installed.rc != 0

- name: Install elasticdump
  ansible.builtin.command: npm install elasticdump -g
  register: result

- name: Debug install elasticdump
  ansible.builtin.debug:
    var: result

- name: Make a symlink to /usr/bin location
  ansible.builtin.file:
    src: /usr/local/bin/elasticdump
    dest: /usr/bin/elasticdump
    state: link
